# Generated by Django 3.1.7 on 2021-03-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dormanscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecodes',
            options={'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
