# Generated by Django 3.1.7 on 2021-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormanscraper', '0002_auto_20210327_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='documents/')),
                ('result_file', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.DeleteModel(
            name='FileCodes',
        ),
    ]
