# Generated by Django 3.1.7 on 2021-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormanscraper', '0003_auto_20210327_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='len_codes',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
