# Generated by Django 3.1.7 on 2021-03-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormanscraper', '0004_project_len_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='len_codes',
            field=models.CharField(max_length=50),
        ),
    ]
